---
title: "Navicore POC Workbook"
author: ejs
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: false
  pdf_document:
    toc: true
    number_sections: true
    highlight: haddock
fontsize: 12pt
geometry: margin=.5in
---

HOWTO
========

###Pull data

save k8s data in data dir

```
kubectl get pods --all-namespaces -o "custom-columns=POD:metadata.name,NAMESPACE:metadata.namespace,NODE:spec.nodeName,CPU_LIMITS:spec.containers[*].resources.limits.cpu,MEM_LIMITS:spec.containers[*].resources.limits.memory" > data/nodes.text
```

###Create report

```
./build.sh
```

At this point, you are done.  Find the final pdf report generated by the
`build.sh` script in the root dir of this repository.

If the report requires further explanation, read on...

Load Data
========

The JSON data is loaded into a dataframe ...

```{r load, fig.width=7, fig.height=7, message=FALSE, echo=FALSE}
library(tidyverse)

# Read the file, assuming the file is whitespace-delimited
data <- read.table("data/nodes.text", header=TRUE, sep="")
data$NAMESPACE <- as.factor(data$NAMESPACE)
data$NODE <- as.factor(data$NODE)

# Aggregate data
data_aggregated <- data %>%
  group_by(NODE, NAMESPACE) %>%
  summarise(PodCount = n(), .groups = 'drop') # Ensure the group_by effect is properly terminated

# Create faceted pie charts
ggplot(data_aggregated, aes(x="", y=PodCount, fill=NAMESPACE)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar(theta = "y") + # Transform the bar plot into a pie chart
  facet_wrap(~ NODE) + # Create a separate pie chart for each node
  labs(x = NULL, y = NULL, fill = "Namespace") +
  theme_void() + # Use theme_void to remove most of the background, gridlines, and text
  theme(legend.title = element_text(size = 12), legend.text = element_text(size = 10)) # Adjust the legend appearance
